// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package playback

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureMediaPlayerSurface string = "rc(Windows.Media.Playback.MediaPlayerSurface;{0ed653bc-b736-49c3-830b-764a3845313a})"

type MediaPlayerSurface struct {
	ole.IUnknown
}

//func (impl *MediaPlayerSurface) GetCompositionSurface() (*composition.ICompositionSurface, error) {
//	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlayerSurface))
//	defer itf.Release()
//	v := (*iMediaPlayerSurface)(unsafe.Pointer(itf))
//	return v.GetCompositionSurface()
//}
//
//func (impl *MediaPlayerSurface) GetCompositor() (*composition.Compositor, error) {
//	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlayerSurface))
//	defer itf.Release()
//	v := (*iMediaPlayerSurface)(unsafe.Pointer(itf))
//	return v.GetCompositor()
//}

func (impl *MediaPlayerSurface) GetMediaPlayer() (*MediaPlayer, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiMediaPlayerSurface))
	defer itf.Release()
	v := (*iMediaPlayerSurface)(unsafe.Pointer(itf))
	return v.GetMediaPlayer()
}

func (impl *MediaPlayerSurface) Close() error {
	itf := impl.MustQueryInterface(ole.NewGUID(foundation.GUIDIClosable))
	defer itf.Release()
	v := (*foundation.IClosable)(unsafe.Pointer(itf))
	return v.Close()
}

const GUIDiMediaPlayerSurface string = "0ed653bc-b736-49c3-830b-764a3845313a"
const SignatureiMediaPlayerSurface string = "{0ed653bc-b736-49c3-830b-764a3845313a}"

type iMediaPlayerSurface struct {
	ole.IInspectable
}

type iMediaPlayerSurfaceVtbl struct {
	ole.IInspectableVtbl

	GetCompositionSurface uintptr
	GetCompositor         uintptr
	GetMediaPlayer        uintptr
}

func (v *iMediaPlayerSurface) VTable() *iMediaPlayerSurfaceVtbl {
	return (*iMediaPlayerSurfaceVtbl)(unsafe.Pointer(v.RawVTable))
}

//func (v *iMediaPlayerSurface) GetCompositionSurface() (*composition.ICompositionSurface, error) {
//	var out *composition.ICompositionSurface
//	hr, _, _ := syscall.SyscallN(
//		v.VTable().GetCompositionSurface,
//		uintptr(unsafe.Pointer(v)),    // this
//		uintptr(unsafe.Pointer(&out)), // out composition.ICompositionSurface
//	)
//
//	if hr != 0 {
//		return nil, ole.NewError(hr)
//	}
//
//	return out, nil
//}
//
//func (v *iMediaPlayerSurface) GetCompositor() (*composition.Compositor, error) {
//	var out *composition.Compositor
//	hr, _, _ := syscall.SyscallN(
//		v.VTable().GetCompositor,
//		uintptr(unsafe.Pointer(v)),    // this
//		uintptr(unsafe.Pointer(&out)), // out composition.Compositor
//	)
//
//	if hr != 0 {
//		return nil, ole.NewError(hr)
//	}
//
//	return out, nil
//}

func (v *iMediaPlayerSurface) GetMediaPlayer() (*MediaPlayer, error) {
	var out *MediaPlayer
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetMediaPlayer,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out MediaPlayer
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
