// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package protection

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

type MediaPlaybackItem struct {
	ole.IUnknown
}

const SignatureServiceRequestedEventArgs string = "rc(Windows.Media.Protection.ServiceRequestedEventArgs;{34283baf-abb4-4fc1-bd89-93f106573a49})"

type ServiceRequestedEventArgs struct {
	ole.IUnknown
}

func (impl *ServiceRequestedEventArgs) GetRequest() (*IMediaProtectionServiceRequest, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiServiceRequestedEventArgs))
	defer itf.Release()
	v := (*iServiceRequestedEventArgs)(unsafe.Pointer(itf))
	return v.GetRequest()
}

func (impl *ServiceRequestedEventArgs) GetCompletion() (*MediaProtectionServiceCompletion, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiServiceRequestedEventArgs))
	defer itf.Release()
	v := (*iServiceRequestedEventArgs)(unsafe.Pointer(itf))
	return v.GetCompletion()
}

func (impl *ServiceRequestedEventArgs) GetMediaPlaybackItem() (*MediaPlaybackItem, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiServiceRequestedEventArgs2))
	defer itf.Release()
	v := (*iServiceRequestedEventArgs2)(unsafe.Pointer(itf))
	return v.GetMediaPlaybackItem()
}

const GUIDiServiceRequestedEventArgs string = "34283baf-abb4-4fc1-bd89-93f106573a49"
const SignatureiServiceRequestedEventArgs string = "{34283baf-abb4-4fc1-bd89-93f106573a49}"

type iServiceRequestedEventArgs struct {
	ole.IInspectable
}

type iServiceRequestedEventArgsVtbl struct {
	ole.IInspectableVtbl

	GetRequest    uintptr
	GetCompletion uintptr
}

func (v *iServiceRequestedEventArgs) VTable() *iServiceRequestedEventArgsVtbl {
	return (*iServiceRequestedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iServiceRequestedEventArgs) GetRequest() (*IMediaProtectionServiceRequest, error) {
	var out *IMediaProtectionServiceRequest
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetRequest,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out IMediaProtectionServiceRequest
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iServiceRequestedEventArgs) GetCompletion() (*MediaProtectionServiceCompletion, error) {
	var out *MediaProtectionServiceCompletion
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetCompletion,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out MediaProtectionServiceCompletion
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiServiceRequestedEventArgs2 string = "553c69d6-fafe-4128-8dfa-130e398a13a7"
const SignatureiServiceRequestedEventArgs2 string = "{553c69d6-fafe-4128-8dfa-130e398a13a7}"

type iServiceRequestedEventArgs2 struct {
	ole.IInspectable
}

type iServiceRequestedEventArgs2Vtbl struct {
	ole.IInspectableVtbl

	GetMediaPlaybackItem uintptr
}

func (v *iServiceRequestedEventArgs2) VTable() *iServiceRequestedEventArgs2Vtbl {
	return (*iServiceRequestedEventArgs2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iServiceRequestedEventArgs2) GetMediaPlaybackItem() (*MediaPlaybackItem, error) {
	var out *MediaPlaybackItem
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetMediaPlaybackItem,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out playback.MediaPlaybackItem
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
